### PR TITLE
XSL conversion nouvelle terminologie segmOnto

### PR DESCRIPTION
**Pull request by ArianePinche**

### CODE REVIEW

**Comment by gabays** [comment]
Super idea!, super useful I wonder if it is the best place though. We discussed the creation of a `Transformation scripts` repo. Don't you think it would be better?

**Comment by ArianePinche** [comment]
Maybe not the best place, I just wanted to make it quickly usable.

**Comment by gabays** [comment]
I suggest creating a repo `TransformationScripts` with a directory `ALTO2ALTO`, in which I put the script. I can do it now, so we do not lose time. Otherwise if you really prefer to put here, tell me I merge immediately

**Comment by ArianePinche** [comment]
completely ok for the new repo

**Comment by gabays** [comment]
C'est bon pour toi? https://github.com/SegmOnto/Scripts/blob/master/ALTO2ALTO/alto-update-draft-segmonto.xsl

**Comment by ArianePinche** [comment]
Parfait

**Review by gabays — CHANGES_REQUESTED** [review]
Close PR and delete the branch. Problem solved

**Pull request closed without merging**
