### PR TITLE
add images+subtypes+spelling corrections

### PR DESCRIPTION
**Pull request by gabays**
@Jean-Baptiste-Camps as promised, my homework

### CODE REVIEW

**Comment by Jean-Baptiste-Camps** [comment]
Nice ! I'll have a detailed look on that soon.

**Comment by Jean-Baptiste-Camps** [comment]
I've made some more modifications, subtypes and cleaning !

**Comment by Jean-Baptiste-Camps** [comment]
We just need to settle on the few pending issues for each zone. After that, I think we'll be good to go.

**Comment by gabays** [comment]
for me it's good. Shall we merge? I think I need you to approve

**Review by Jean-Baptiste-Camps — APPROVED** [review]

**Pull request merged**
