### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Jean-Baptiste-Camps**
Solving #17, #19, #21, #25 and #29.

### CODE REVIEW

**Comment by Jean-Baptiste-Camps** [comment]
With that, we should have a SegmOnto alpha, and no more opened issues.

**Review by gabays — APPROVED** [review]

**Comment by gabays** [comment]
I have added my review. I let Ariane do it before merging.

**Review by PonteIneptique — CHANGES_REQUESTED** [review]
- MarginTextZone is in the file nbamed MarginZone.
- The specification of Zone:SubZone#NumberingOrDetail is not described.
- The freetext characteristic of subzone is not defined.

**Comment by gabays** [comment]
- We switched from `MarginZone` to `MarginTextZone` at the last minute. We probably forgot that… Thx
- Regarding the two other remarks, it should be described elsewhere. I am currently writing the doc (cf. [issue open here](https://github.com/SegmOnto/SegmOnto.github.io/issues/1).)

**Comment by PonteIneptique** [comment]
The repository you're mentioning is probably private.
I still think a note in the readme would be welcome.

**Comment by gabays** [comment]
You are right for both

**Comment by Jean-Baptiste-Camps** [comment]
A note in the README, or preferably an introduction to the Guidelines, giving general considerations, of the type:

 There are two classes of regions: zones (an area, i.e., polygon, on the page) and lines (an area, plus a baseline). 
 
Zones or lines can be caracterised by:
 
- a `type` (mandatory)
- a `subtype` (optional)
- a `number` (optional)

of the form

`Region(:subtype)?(#\d)?`

e.g.

`MainZone`

or

`MainZone:column#1`

**Comment by gabays** [comment]
It is not perfect, but:
Screenshot 2021-11-23 at 08 18 28

**Comment by gabays** [comment]
New version
```xml
<div rend="toc" xml:id="guidelines">
   <head>Guidelines</head>
   <p>We have distributed the elements of our vocabulary according to the tree-like tessellation of
      a page:
      <list>
         <item>The page contains zones</item>
         <item>A zone contains lines</item>
      </list>
   </p>
   <p>The annotation uses:
      <list>
         <item><hi rend="italic">Types</hi>, which are mandatory and whose values are closed</item>
         <item><hi rend="italic">Subtypes</hi>, which are optional and whose values are suggested
            but open</item>
         <item><hi rend="italic">Numbering</hi>, which are optional and whose values are suggested
            but open</item>
      </list>
   </p>
   <p>These three options are available for three reasons:
      <list>
         <item>Homogenise the data, to facilitate the exchange and the pooling of annotated data</item>
         <item>Adapt to a maximum of possible scenarii, and offer, when needed, some semantic information
            via the subtypes (types being potentially too poor).</item>
         <item>Ease the training of models by differentiating zones or lines (<val>Main#1</val>
            for the column on the left and <val>Main#2</val> for the column on the right might
            be of a certain help).</item>
      </list>
   </p>
   <p>The syntax is the following: <val>Region(:subtype)?(#\d)?</val>/<val>Type:Subtype#2</val>.
      <eg xml:space="preserve"><![CDATA[
Type:Subtype#Numbering
GraphicZone:Decoration#1
MusicZone:MusicLine
Custom:Entry#2
            ]]></eg>
   </p>
```

**Comment by gabays** [comment]
@Jean-Baptiste-Camps tu modifies ta coquille `MarginTextZone` vs `MarginZone` pour merger?

**Comment by Jean-Baptiste-Camps** [comment]
Done, can you merge ?

**Comment by gabays** [comment]
Apparently you did merge without review, so it is OK?

**Pull request merged**
